#!/bin/sh

case $1 in
	disable)
		ver=$(grep "ver=" "disable/tmp/tweakprop.sh" | cut -d= -f2)
		zip -6urv disable-navbar-${ver}.zip disable/;;
	enable)
		ver=$(grep "ver=" "enable/tmp/tweakprop.sh" | cut -d= -f2)
		zip -6urv enable-navbar-${ver}.zip enable/;;
esac
